name: dart_scripts
description: Some useful dart scripts for me.
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.0
  file: ^6.1.0
  html: ^0.15.0
  http: ^0.13.0
  path: ^1.8.0
  toml: ^0.13.0

dev_dependencies:
  benchmarking: ^0.6.0
  lint: ^2.0.0
  mockito: ^5.0.0
  test: ^1.0.0


executables:
  # dart pub global activate --source path E:\Code\dart_scripts
  split-novels: split_novels
  rename-savefiles: rename_renpy_savefiles
  myalias: command_alias
